### ISSUE TITLE
Feature Request: Class State Invariant

### ISSUE THREAD

**Issue by liufengyun** [epfl-lara/leon#103] opened 2015-05-17 15:23 UTC
I'm not sure if this is the right place to ask for a feature. The problem I encountered is that I want to impose a constraint on all instances of a class. For example, in the following I'd like `isValid` to hold for all instances of `GoSet`.

``` scala
case class GoSet[T](elements: List[T]) {
  def isValid: Boolean = {
    if (isEmpty) true
    else !GoSet(elements.tail).contains(elements.head) && GoSet(elements.tail).isValid
  }
}
```

As far as I know currently Leon doesn't support specifying an invariant on a class, so I have to duplicate `require(isValid)` at the beginning of each member method. With the support of class state invariant, it not only helps save duplicate code, but also enables programmers to think about verification at a higher abstraction level.

From the functional point of view, the class invariant are actually the post-condition of the constructor of the class(assume immutable objects). It seems this is theoretically possible for immutable objects, but I'm not sure about the details.

Thanks.

**Comment by manoskouk** [comment] 2015-05-22 12:13
Hi Liu,

this is actually something we have been planning to do for a while now, but nobody has found the time yet.
If you are interested to getting involved, it will be done that much sooner!

**Comment by liufengyun** [comment] 2015-05-22 18:16
Thanks @manoskouk . 

I'm interested, maybe I can hack it after the exam in my spare time. Talk to you then.

**Comment by colder** [comment] 2015-05-26 12:05
The difficulty with invariants can be decomposed in two problems:

## Problem 1

Given

    case class A(a: BigInt) {
      require(a > 0)
    }

You will have to inject this requirement in preconditions of all functions taking ```A```, so

    def foo(a: A) = { 
      a.a
    } ensuring { _ > 0 }

will need to become:

    def foo(a: A) = { 
      require(a.a > 0)
      a.a
    } ensuring { _ > 0 }

While trivial for this case, consider the following functions:

    def foo2(as: List[A]) = { 
      require(as.nonEmpty)
      a.head.a
    } ensuring { _ > 0 }

    def foo3(as: Set[A]) = { 
      as contains a
    } ensuring { _ > 0 }

Here it is not so easy to constraint ```foo2``` so that the list contains only valid ```A```s. Moreover, it is impossible to specify that the ```Set[A]``` contains only valid ```A```s as Leon lacks capabilities to traverse the set.


## Problem 2

While it would be practical to write the following function:

    case class A(a: BigInt) {
      require(isValid)
      def isValid: Boolean = // ...
    }

You have a chicken&egg issue, where isValid would be injected with a precondition checking isValid on $this.


I believe both problems can be solved (or we can restrict the usage of these invariants), but they constitute the reasons why class invariants have you been trivially implemented yet.

**Comment by psuter** [comment] 2015-05-26 12:50
@colder: I'm not sure your description of Problem 1 is the most straightforward way to look at the problem. Rather than enforcing the constraint on `A` at the entry point of functions taking `A`s, the assume/guarantee way of doing things would be to check the constraint at the creation point, ie wherever the constructor is invoked. Within `foo`, you then get to assume that invariants on `A`s always hold. This is of course making the standard closed-world hypothesis. The chicken and egg problem stands, but you could treat `this` differently (ie not use the guarantees of `A` in that context). Recursive types will be particularly interesting (you get to assume the property on subtrees to prove it on the whole).

**Comment by liufengyun** [comment] 2015-05-26 15:40
For the second problem, it seems it's possible to use an annotation like `@invariant` to specify class invariant. This way Leon can treat the method differently because of the annotation. This approach is more friendly than forcing users to specify class invariants in a companion object.

**Comment by psuter** [comment] 2015-05-26 15:57
@liufengyun I don't think we need the companion object in any case; in the example @colder gave, the invariant is written in the body of the case class (which is really the body of the constructor). This is consistent with the style of (function) preconditions in Leon.

One way to approach the problem is to reduce it to what exists in Leon, i.e. pre- and postconditions on functions. (Note that I'm not suggesting the implementation follows the same idea.)

For any case class with an invariant:

    case class A(a1: T1, ..., an: Tn) {
      require(invariant(a1,...,a2))
    }

we can introduce a constructor function:

    def makeA(a1: T1, ..., an: Tn) : A = {
      require(invariant(a1,...,a2))
      A(a1,...,an)
    }

and a dereference function:

    def readA(a: A) : A = {
      a
    } ensuring(res => invariant(res.a1,...,res.an))

If we then replace every constructor invocation `A(a1,...,an)` with `makeA(a1,...,an)` and every assignment `val a : A = expr` with `val a : A = readA(expr)`, I believe we get the full power of class invariants: the invariant is checked and enforced at construction time, and can be relied upon at reading time. This is all using Leon's standard unfolding/proof mechanisms.

Note that we do not need to prove the postcondition of `readA` as long as we can make sure that all instances of `A` are created through `makeA` (that is where the closed-world assumption comes in).

Also note that we already follow this pattern in many benchmarks, using `inv(...)` as a pre- and postcondition throughout programs. Having the invariant stated as part of the data representation would be cleaner (and more OO-like).

**Comment by liufengyun** [comment] 2015-05-26 16:14
@psuter I mean to use companion objects to solve the egg-and-chicken problem. I agree the approach you described seems to be an elegant solution to the first problem, it just requires systematic rewriting of the AST.

**Comment by colder** [comment] 2015-05-28 13:05
One issue with ```makeA```/```readA``` is that it is not required that values are explicitly read and/or created in order for them to be present in a counter-example:

    case class Rat(n: BigInt, d: BigInt) {
      require(d != 0)
    }
  
    def plop(list: List[Rat]) = {
      list
    } ensuring { _ == Nil[Rat]() }

Here the counter-example would be ```List(Rat(0,0))``` which is invalid w.r.t. Rat.

**Comment by psuter** [comment] 2015-05-28 14:03
@colder good point. Do you think it's enough to "propagate" class invariants to classes that have other classes as fields?

E.g. if I have:

    case class A(x : BigInt) { require(x != 0) }
    case class B(a : A)

then `B` implicitly gets the invariant `require(a.x != 0)`. (Not 100% sure how generics are handled, but presumably the types are expanded "à la C++" by the time the constraints get to the solver and it can be done then.)

**Comment by samarion** [comment] 2016-04-25 08:55
Supported since https://github.com/epfl-lara/leon/commit/6a517bc3fca8ebe503a5abac430353fe48256aec

**Closed by samarion** 2016-04-25 08:55 UTC
Labels: enhancement
